### ISSUE TITLE
*.d.ts, *.js, and *.metadata.json files are getting generated in my src directory when using angular 2 barrels

### ISSUE THREAD

**Issue by tadchristiansenli** [driftyco/ionic-app-scripts#136]
*.d.ts, *.js, and *.metadata.json files are getting generated in my src directory when using angular 2 barrels. If I remove the barrel, then they are not generated in the src directory.

It would be nice if they were not put in the src directory because when you try and build again the linter and the build fails because it is not expecting those files to be there.

**Steps to reproduce:**
1. Create a barrel for a one of your ts files (I tried putting it both outside and inside the source directory and still had the issue)
2. Update you other ts files to use the barrel to import the class in the ts file.
3. Run "ionic run android"

**Result**
*.d.ts, *.js, and *.metadata.json files are get generate next to the *.ts files in the src directory (at least the ones using barrels do)

```
"scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"
  },
  "config": {
    "ionic_rollup": "./scripts/rollup.config.js"
  }
```

**Which @ionic/app-scripts version are you using?**
ionic CLI 2.1.0
ionic 2 RC0
angular 2.0.1
@ionic/app-scripts 0.0.30 (latest)

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! I am going to close this issue as a duplicate of https://github.com/driftyco/ionic-app-scripts/issues/105.

**Comment by tadchristiansenli** [comment]
@jgw96 Is this really the same issue? They were getting the following error:
`Error: Module .../ionic/src/app/index.ts does not export ComponentData (imported by .../src/components/module-components/module-component/module-component.ts) at Module.trace (.../node_modules/rollup/dist/rollup.js:7706:29)`

I am not getting that error. It builds fine if I delete all those files. I am just getting metadata files generated in my source directory when using barrels. Help me understand how this is the same issue as #105

**Comment by tadchristiansenli** [comment]
@jgw96 I am not trying to be annoying. I know you guys are hard at work fixing things. I just want to make sure my issue doesn't get lost. Are you sure this is the same issue as #105? It has to do with barrels, but it appears to me to be a separate issue for me. Would you be able to clarify why you think this is the same issue.

Thanks for ionic and keep up the good work!

**Comment by kleeb** [comment]
Look like its fixed with Ionic RC1 + Angular 2.1.0.

**Comment by marcsyp** [comment]
I have updated my app to RC2 and still having this problem.  Is it possible that I have some leftover build options that are still screwing things up?  Any ideas?

Thanks,
Marc

**Comment by marcsyp** [comment]
For information...

tsconfig.json:

`{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5"
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}`

And tsconfig.tmp.json:

`{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5",
    "outDir": "{{MyRepo}}\\.tmp"
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  },
  "include": [
    "{{MyRepo}}\\src\\app\\main.dev.ts",
    "{{MyRepo}}\\msyp\\Documents\\Bitbucket\\immersive-patient-room\\src\\**\\*.d.ts"
  ]
}
`

It seems like the "include" section might be causing problems? No idea.

**Comment by kleeb** [comment]
add 

```
  "include": [
    "src/**/*.ts"
  ]
```

in your tsconfig

**Comment by marcsyp** [comment]
Thanks for the response -- unfortunately that didn't help.  Also tried changing "sourceMap" to false, as I thought maybe that was part of it, but no change.  Any other ideas?

Thanks.

**Comment by marcsyp** [comment]
The good news is that for some reason the build is not failing anymore, at the very least... still wondering why all these files started appearing in my src folder...

**Comment by tadchristiansenli** [comment]
They are needed for AoT compilation.
