### ISSUE TITLE
[RC1] Templates in external .html file not found

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-app-scripts#167]
_From @basvdijk on October 14, 2016 14:8_

#### Short description of the problem:

The template files are searched in the wrong path (`src/src` instead of `src`):
`ionic-app/src/src/pages/Settings/Settings.html`

#### What behavior are you expecting?
The templates being searched in:
`ionic-app/src/pages/Settings/Settings.html`

My component:

```
@Component({
    templateUrl: 'Settings.html'
})

export class Settings {
```

I've also tried `./Settings.html`

My package.json:

```
  "dependencies": {
    "@angular/common": "^2.0.0",
    "@angular/compiler": "^2.0.0",
    "@angular/compiler-cli": "^0.6.2",
    "@angular/core": "^2.0.0",
    "@angular/forms": "^2.0.0",
    "@angular/http": "^2.0.0",
    "@angular/platform-browser": "^2.0.0",
    "@angular/platform-browser-dynamic": "^2.0.0",
    "@angular/platform-server": "^2.0.0",
    "ionic-angular": "^2.0.0-rc.1",
    "ionicons" : "^3.0.0",
    "@ionic/storage": "^1.0.3",
    "ionic-native": "^2.0.3",
    "rxjs": "^5.0.0-beta.12",
    "zone.js": "^0.6.21",


    "ng2-cordova-oauth": "^0.0.6",
    "ng2-translate": "^3.0.0",
    "angular2-google-maps": "^0.15.0",
    "angular2-moment": "^1.0.0-beta.1",
    "font-awesome": "^4.6.3"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^0.0.33",
    "typescript": "^2.0.3"
  },
```
 

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a
```

_Copied from original issue: driftyco/ionic#8708_

**Comment by danbucholtz** [comment]
This is fixed is master now.

Will let you know when to test @basvdijk.

Thanks,
Dan

**Comment by basvdijk** [comment]
@danbucholtz thanks, appreciated. Any thoughts on when this will be released?

**Comment by danbucholtz** [comment]
Not sure. Can you test it for me quick? I'm waiting for more feedback.  See instructions [here](https://github.com/driftyco/ionic-app-scripts/issues/160#issuecomment-253827102).

Should take 30 seconds to implement change to test.

Thanks,
Dan

**Comment by basvdijk** [comment]
@danbucholtz commented the suggested line and error got away 👍

**Comment by danbucholtz** [comment]
@basvdijk,

w00t! I now have three positive tests. Expect to see that fix land today.

Thanks,
Dan

**Comment by ezekjh** [comment]
Hi,
Having this issue with --dev build only.
Commenting out the mentioned line in transpile.js gets rid of the errors about not finding the templates, but main.js and main.css files are not created.
Prod build compiles fine and the app runs.

**Comment by danbucholtz** [comment]
We released a new CLI and a new app-scripts

```
npm install -g ionic@latest
npm install @ionic/app-scripts
```

I'll re-open if needed. Closing for now.

Thanks,
Dan

**Comment by ezekjh** [comment]
I'm still having this issue with dev build.

> _[11:03:28]  Error reading template file, "csi-code-list.component.html": Error: ENOENT: no such file            or directory, open 'C:\xxxxxxx\src\src\app\inspections\item-detail\component\csi-code-list.component.html'_

Here's the output of ionic info:
_Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.31
OS: Windows 8.1
Node Version: v6.3.1_

**Comment by danbucholtz** [comment]
@ezekjh,

Can you install the latest app-scripts?

```
npm install @ionic/app-scripts@latest
```

Thanks,
Dan

**Comment by sdsanders** [comment]
Updating to the newest app-scripts fixed this for me.

**Comment by ezekjh** [comment]
Hi @danbucholtz, sorry about that.. First time I did a npm install of latest but didn't update at all.. Had to change some dependencies on node_modules.
Now it's working fine.
Thank you.

**Comment by jcviau** [comment]
Ensure your tsconfig.json doesnt have any outDir, otherwise the latest version (0.0.36) use this path to search html.
