### ISSUE TITLE
[rc1] barrels not working when build with ionic run android

### ISSUE THREAD

**Issue by jamavi** [driftyco/ionic-app-scripts#189]
Hi,
I update ionic-app-script in order to fix issue  [#154](https://github.com/driftyco/ionic-app-scripts/issues/154) 
"ionic serve -l" works fine with version 0.0.36 but "ionic run android" failed.
Here is my output:

```
[22:45:29]  lint started ...
[22:45:33]  lint finished in 3.81 s
[22:45:33]  can't resolve module ../reducers from /path/to/app/folder/.tmp/app/app.module.ts
[22:45:33]  Error: can't find symbol undefined exported from module /path/to/app/folder/.tmp/reducers/index.ts,
            resolving symbol AppModule in /path/to/app/folder/.tmp/app/app.module.ts,
            resolving symbol AppModule in /path/to/app/folder/.tmp/app/app.module.ts
[22:45:33]  ngc failed
[22:45:33]  ionic-app-script task: "build"
[22:45:33]  Error: Error
```

**Which @ionic/app-scripts version are you using?**
0.0.36

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Related issues: [#154](https://github.com/driftyco/ionic-app-scripts/issues/154)

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
OS: W10
Node Version: v6.7.0

**Comment by jgw96** [comment]
Hello @jamavi ! Thanks for using Ionic! Unfortunately I am not able to reproduce this issue locally. Would you mind posting a repo i can use to reproduce this issue?

**Comment by jamavi** [comment]
Here is a [repo] (https://github.com/jamavi/ionic2-example) to reproduce.

I clone the ionic conference app and add some of my reducers functions. I am used @ngrx/store in the project.
Finally I think that the issue is not the same as [#154](https://github.com/driftyco/ionic-app-scripts/issues/154) but it is also an import problem. The build process can not import my reducer root function from reducers/index.ts.
"ionic serve -l" works but "ionic run android failed"

**Comment by jamavi** [comment]
More precision on the issue: "ionic run android" can not import class/function which is exposed via 
export default
``
// actions/index.ts
export default [
  UserActions,
  NotificationsActions
];
// app.module.ts
import actions from '../actions';
``
This does'nt work with "ionic run android"

**Comment by NoNameProvided** [comment]
I have the same issue. A quick fix is to use the `0.0.29` version of app-scripts. Its working with RC.1 as well.

**Comment by danbucholtz** [comment]
@jamavi,

This is fixed in the latest. Tomorrow we are releasing `@ionic/app-scripts@0.0.37` which has a ton of bug fixes so it may be worth updating to that.

Thanks,
Dan

**Comment by jamavi** [comment]
Hi @danbucholtz 

I just update the [repo](https://github.com/jamavi/ionic2-example) set for this bug to `@ionic/app-scripts@0.0.39`. The bug still exists when run `ionic run android`.
Log output
```
> ionic-app-scripts build

[13:10:31]  ionic-app-scripts 0.0.39
[13:10:31]  build prod started ...
[13:10:31]  clean started ...
[13:10:31]  clean finished in 6 ms
[13:10:31]  copy started ...
[13:10:31]  ngc started ...
[13:10:31]  copy finished in 207 ms
[13:10:31]  lint started ...
[13:10:34]  can't resolve module ../reducers from /path/to/app/folder/.tmp/app/app.module.ts
[13:10:34]  Error: can't find symbol undefined exported from module
            /path/to/app/folder/.tmp/reducers/index.ts, resolving symbol AppModule in
           /path/to/app/folder/.tmp/app/app.module.ts, resolving symbol AppModule in
           /path/to/app/folder/.tmp/app/app.module.ts
[13:10:34]  ngc failed
[13:10:34]  ionic-app-script task: "build"
[13:10:34]  Error: Error
```

**Comment by danbucholtz** [comment]
@jamavi,

We'll take a look.

Thanks,
Dan
