### ISSUE TITLE
Cannot find module ionic-angular/components/toolbar/toolbar-item.ngfactory

### ISSUE THREAD

**Issue by basvdijk** [driftyco/ionic-app-scripts#214]
#### Short description of the problem:

When running `ionic build android` I'll get the error:

`Cannot find module '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory'.`

**Which @ionic/app-scripts version are you using?**

ionic-app-scripts 0.0.36

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

```
[16:23:34]  ngc failed
[16:23:34]  ionic-app-script task: "build"
[16:23:34]  Error: Error

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build" "--color"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! drammer@0.0.1 build: `ionic-app-scripts build`
npm ERR! Exit status 1
```

**Comment by cjpollard** [comment]
Seeing the same issue.

**Comment by jgw96** [comment]
Hello all! Can you make sure that your package.json matches the one [here](https://github.com/driftyco/ionic2-app-base/blob/master/package.json) and then remove `node_modules` and run `npm install`? Thanks!

**Comment by basvdijk** [comment]
Thanks this helped! It turned out all the 2.0.0 packages were listed as 2.1.1 in py package.json

**Comment by cjpollard** [comment]
That fixed it, thanks.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! I am going to close this issue for now as it seems to have been fixed.

**Comment by janein** [comment]
Hi,

after upgrading to rc2 I got a similar error, the same as described in this issue: https://github.com/arkon/ng2-inline-svg/issues/13

Deleting everything and reinstalling didn't solve it.
