### ISSUE TITLE
Ionic serve failed

### ISSUE THREAD

**Issue by bmbraga** [driftyco/ionic-app-scripts#232]
Can anyone help me with this problem?
The server does not create files and the build is not successfully done.

[16:29:50]  tslint: ...reno/Dropbox/Apps/src/services/bmbraga.http.ts,
       L3:  import { Injectable }     from '@angular/core';
       L4:  import { Http, Response, Headers, RequestOptions } from '@angular/http';
       L5:  import {Observable} from 'rxjs/Rx';

            line: 5
            Unused import: 'Observable'

       L4:  import { Http, Response, Headers, RequestOptions } from '@angular/http';
       L5:  import {Observable} from 'rxjs/Rx';

[16:29:51]  tslint: ...ox/Apps/src/pages/item-details/item-details.ts,
            line: 87
            Unused variable: 'alert'

      L86:  console.log("login error: " + JSON.stringify(error));
      L87:  try {
      L88:      let alert = this.alertCtrl.create({

[16:29:51]  tslint: .../Apps/src/pages/search-result/search-result.ts,
            line: 84
            Unused variable: 'alert'

      L83:  try {
      L84:      let alert = this.alertCtrl.create({
      L85:              title: 'Server error',

[16:29:51]  tslint: ...sers/Breno/Dropbox/Apps/src/pages/home/home.ts,
            line: 2
            Unused import: 'NavParams'

[16:29:51]  tslint: ...sers/Breno/Dropbox/Apps/src/pages/home/home.ts,
       L1:  import { Component } from '@angular/core';
       L2:  import { NavController, NavParams, Platform } from 'ionic-angular';
       L3:  import { AlertController } from 'ionic-angular';

            line: 98
            Unused variable: 'alert'

      L97:  try {
      L98:      let alert = this.alertCtrl.create({
      L99:              title: 'Server error',

[16:29:51]  tslint: .../Apps/src/pages/letter-result/letter-result.ts,
            line: 97
            Unused variable: 'alert'

      L96:  try {
      L97:      let alert = this.alertCtrl.create({
      L98:              title: 'Server error',

[16:29:51]  lint finished in 12.81 s
[16:29:54]  typescript: .../Dropbox/Apps/src - Copia/app/app.component.ts,
            line: 37
            Property 'analytics' does not exist on type 'Window'.

      L36:  try {
      L37:      window.analytics.startTrackerWithId("UA-960473-35");
      L38:  } catch (e) {

[16:29:54]  typescript: ...no/Dropbox/Apps/src - Copia/pages/home/home.ts,
            line: 27
            Supplied parameters do not match any signature of call target.

      L26:  this.block2Items = [];
      L27:  this.[16:29:54]  typescript: ...no/Dropbox/Apps/src - Copia/pages/home/home.ts, l
            line: 34 o
[16:29:54]  typescript: ...no/Dropbox/Apps/src - Copia/pages/home/home.ts, a
            line: 67 d
HomeIte[16:29:54]  typescript: ...TraduzindoSonhos/TraduzindoSonhos/src - Copia/pages/item-details/item-details.ts,
m            line: 29
s();
      L28:  this.trackEvent();

            Property 'analytics' does not exist on type 'Window'.

      L33:  [16:29:54]  typescript: ...TraduzindoSonhos/TraduzindoSonhos/src - Copia/pages/item-details/item-details.ts,
try            line: 36  {

      L34:  [16:29:54]  typescript: ...TraduzindoSonhos/TraduzindoSonhos/src - Copia/pages/item-details/item-details.ts,        window.
a            line: 64 n
alytics.trackEvent("Home");
[16:29:54]  typescript: ...aduzindoSonhos/TraduzindoSonhos/src - Copia/pages/letter-result/letter-result.ts,       L35:
}             line: 31 catch
 (e) {

            Cannot find name 'Response'.

      L67:  dataSuccess(res: Re[16:29:54]  typescript: ...aduzindoSonhos/TraduzindoSonhos/src - Copia/pages/letter-result/letter-result.ts, s
            line: 38 p
onse) {
[16:29:54]  typescript: ...aduzindoSonhos/TraduzindoSonhos/src - Copia/pages/letter-result/letter-result.ts,       L68:
        this.loader.dismiss();

            Supplied parameters do not match any signature of call target.

            line: 71       L28:
this.itemDetails = null;
      L29:  [16:29:54]  typescript: ...aduzindoSonhos/TraduzindoSonhos/src - Copia/pages/search-result/search-result.ts,
t            line: 26 h
is.[16:29:54]  typescript: ...aduzindoSonhos/TraduzindoSonhos/src - Copia/pages/search-result/search-result.ts, l
            line: 33 o
a[16:29:54]  typescript: ...aduzindoSonhos/TraduzindoSonhos/src - Copia/pages/search-result/search-result.ts,
d            line: 66
HomeItems[16:29:54]  typescript: ...rs/Breno/Dropbox/Apps/src/app/app.component.ts, (
            line: 37 )
;
[16:29:54]  typescript: ...sers/Breno/Dropbox/Apps/src/pages/home/home.ts,       L30:
this.trackEvent();

            Property 'analytics' does not exist on type 'Window'.

            line: 27       L35:
try {
      L36:      window.an[16:29:54]  typescript: ...sers/Breno/Dropbox/Apps/src/pages/home/home.ts, a
l            line: 34
ytics.trackEvent("Details");
      L37:  } catch (e) {

            Cannot find name 'Response'.

      L64:  dataSuccess(res: Response) {
      L65:      this.loader.dismiss();

            Supplied parameters do not match any signature of call target.

      L30:  this.letter = this.letter.toUpperCase();
      L31:  [16:29:54]  typescript: ...sers/Breno/Dropbox/Apps/src/pages/home/home.ts,
this.loa            line: 67 d
HomeItems();
      L32:  [16:29:54]  typescript: ...ox/Apps/src/pages/item-details/item-details.ts, this.trackEvent();

            Property 'analytics' does not exist on type 'Window'.

      L37:              line: 29 try
 {
      L38:  [16:29:54]  typescript: ...ox/Apps/src/pages/item-details/item-details.ts,        window.
a            line: 36
nal[16:29:54]  typescript: ...ox/Apps/src/pages/item-details/item-details.ts,
y            line: 64 t
ic[16:29:54]  typescript: .../Apps/src/pages/letter-result/letter-result.ts,
s            line: 31 .trackEvent("LSearch", "Letter", this.letter);

      L39:  } catch (e) {

            Cannot find name 'Response'.

      L71:  [16:29:54]  typescript: .../Apps/src/pages/letter-result/letter-result.ts, dataSuccess(res:
R            line: 38
esponse) {
      L72:      this.loadingItems = false;

            Supplied parameters do not match any signature of call target.

      L25:  this.letter = navParams.get('search');
      L26:  [16:29:54]  typescript: .../Apps/src/pages/letter-result/letter-result.ts,
t            line: 71 h
is.[16:29:54]  typescript: .../Apps/src/pages/search-result/search-result.ts, l
            line: 26 o
adH[16:29:54]  typescript: .../Apps/src/pages/search-result/search-result.ts,
o            line: 33
meIt[16:29:54]  typescript: .../Apps/src/pages/search-result/search-result.ts, e
m            line: 66
s();
      L27:  this.trackEvent();

            Property 'analytics' does not exist on type 'Window'.

      L32:  try {
[16:29:54]  transpile failed       L33:
        window.analytics.trackEvent("LSearch", "Letter", this.letter);
      L34:  } catch (e) {

            Cannot find name 'Response'.

      L66:  dataSuccess(res: Response) {
      L67:      this.loader.dismiss();

            Property 'analytics' does not exist on type 'Window'.

      L36:  try {
      L37:      window.analytics.startTrackerWithId("UA-960473-35");
      L38:  } catch (e) {

            Supplied parameters do not match any signature of call target.

      L26:  this.block2Items = [];
      L27:  this.loadHomeItems();
      L28:  this.trackEvent();

            Property 'analytics' does not exist on type 'Window'.

      L33:  try {
      L34:      window.analytics.trackEvent("Home");
      L35:  } catch (e) {

            Cannot find name 'Response'.

      L67:  dataSuccess(res: Response) {
      L68:      this.loader.dismiss();

            Supplied parameters do not match any signature of call target.

      L28:  this.itemDetails = null;
      L29:  this.loadHomeItems();
      L30:  this.trackEvent();

            Property 'analytics' does not exist on type 'Window'.

      L35:  try {
      L36:      window.analytics.trackEvent("Details");
      L37:  } catch (e) {

            Cannot find name 'Response'.

      L64:  dataSuccess(res: Response) {
      L65:      this.loader.dismiss();

            Supplied parameters do not match any signature of call target.

      L30:  this.letter = this.letter.toUpperCase();
      L31:  this.loadHomeItems();
      L32:  this.trackEvent();

            Property 'analytics' does not exist on type 'Window'.

      L37:  try {
      L38:      window.analytics.trackEvent("LSearch", "Letter", this.letter);
      L39:  } catch (e) {

            Cannot find name 'Response'.

      L71:  dataSuccess(res: Response) {
      L72:      this.loadingItems = false;

            Supplied parameters do not match any signature of call target.

      L25:  this.letter = navParams.get('search');
      L26:  this.loadHomeItems();
      L27:  this.trackEvent();

            Property 'analytics' does not exist on type 'Window'.

      L32:  try {
      L33:      window.analytics.trackEvent("LSearch", "Letter", this.letter);
      L34:  } catch (e) {

            Cannot find name 'Response'.

      L66:  dataSuccess(res: Response) {
      L67:      this.loader.dismiss();

[16:29:54]  watch ready in 17.43 s
Running live reload server: http://localhost:35729
Watching: www/**/*, !www/lib/**/*, !www/**/*.map
√ Running dev server:  http://localhost:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

ionic $ [16:29:54]  copy finished in 17.48 s

**Comment by bmbraga** [comment]
[16:33:05]  Error: Error at C:/Users/Breno/Dropbox/Apps/.tmp/pages/item-details/item-details.ts:29:3
[16:33:05]  Supplied parameters do not match any signature of call target.
[16:33:05]  Error at C:/Users/Breno/Dropbox/Apps/.tmp/pages/item-details/item-details.ts:36:12
[16:33:05]  Property 'analytics' does not exist on type 'Window'.
[16:33:05]  Error at C:/Users/Breno/Dropbox/Apps/.tmp/pages/item-details/item-details.ts:64:19
[16:33:05]  Cannot find name 'Response'.
[16:33:05]  Error at C:/Users/Breno/Dropbox/Apps/.tmp/pages/item-details/item-details.ts:64:19
[16:33:05]  Parameter 'res' of public method from exported class has or is using private name 'Response'.
[16:33:05]  Error at C:/Users/Breno/Dropbox/Apps/.tmp/pages/search-result/search-result.ts:26:3
[16:33:05]  Supplied parameters do not match any signature of call target.
[16:33:05]  Error at C:/Users/Breno/Dropbox/Apps/.tmp/pages/search-result/search-result.ts:33:12
[16:33:05]  Property 'analytics' does not exist on type 'Window'.
[16:33:05]  Error at C:/Users/Breno/Dropbox/Apps/.tmp/pages/search-result/search-result.ts:66:19
[16:33:05]  Cannot find name 'Response'.
[16:33:05]  Error at C:/Users/Breno/Dropbox/Apps/.tmp/pages/search-result/search-result.ts:66:19
[16:33:05]  Parameter 'res' of public method from exported class has or is using private name 'Response'.
[16:33:05]  Error at C:/Users/Breno/Dropbox/Apps/.tmp/pages/home/home.ts:27:3
[16:33:05]  Supplied parameters do not match any signature of call target.
[16:33:05]  Error at C:/Users/Breno/Dropbox/Apps/.tmp/pages/home/home.ts:34:12
[16:33:05]  Property 'analytics' does not exist on type 'Window'.
[16:33:05]  Error at C:/Users/Breno/Dropbox/Apps/.tmp/pages/home/home.ts:67:19
[16:33:05]  Cannot find name 'Response'.
[16:33:05]  Error at C:/Users/Breno/Dropbox/Apps/.tmp/pages/home/home.ts:67:19
[16:33:05]  Parameter 'res' of public method from exported class has or is using private name 'Response'.
[16:33:05]  Error at C:/Users/Breno/Dropbox/Apps/.tmp/pages/letter-result/letter-result.ts:31:3
[16:33:05]  Supplied parameters do not match any signature of call target.
[16:33:05]  Error at C:/Users/Breno/Dropbox/Apps/.tmp/pages/letter-result/letter-result.ts:38:12
[16:33:05]  Property 'analytics' does not exist on type 'Window'.
[16:33:05]  Error at C:/Users/Breno/Dropbox/Apps/.tmp/pages/letter-result/letter-result.ts:71:19
[16:33:05]  Cannot find name 'Response'.
[16:33:05]  Error at C:/Users/Breno/Dropbox/Apps/.tmp/pages/letter-result/letter-result.ts:71:19
[16:33:05]  Parameter 'res' of public method from exported class has or is using private name 'Response'.
[16:33:05]  Error at C:/Users/Breno/Dropbox/Apps/.tmp/app/app.component.ts:37:12
[16:33:05]  Property 'analytics' does not exist on type 'Window'.
[16:33:05]  ngc failed
[16:33:05]  ionic-app-script task: "build"
[16:33:05]  Error: Error

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build" "--color"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! TraduzindoSonhos@ build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TraduzindoSonhos@ build script 'ionic-app-scripts build'.
npm ERR! This is most likely a problem with the TraduzindoSonhos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs TraduzindoSonhos
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls TraduzindoSonhos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Breno\Dropbox\Apps\npm-debug.log
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by mhartington** [comment]
Don't serve your project from the Dropbox folder.
The dropbox folder is a common cause of problems for many node scripts.
Moving the app to a different directory should fix the serve issues.

You also have a lot of linting errors that you should fix. It will help make the error readout clearer by removing all the extra noise.

**Comment by bmbraga** [comment]
@mhartington I made copies it to a folder, check the permissions, and still not concluded. Also updated the script to 0.0.37 and even then an error occurs. The ionic Server does not create the main file main.js and get the blank page.

**Comment by bmbraga** [comment]
@mhartington The strangest thing in this problem is that the same application on Windows 8 with ionic 2.1.0-beta-1 compiles without problems, and atul version on windows 10 is it.

**Comment by mhartington** [comment]
You have errors in your code that you need to fix. The output is telling you what you need to fix.

```
[16:33:05] Error: Error at C:/Users/Breno/Dropbox/Apps/.tmp/pages/item-details/item-details.ts:29:3
[16:33:05] Supplied parameters do not match any signature of call target.
[16:33:05] Error at C:/Users/Breno/Dropbox/Apps/.tmp/pages/item-details/item-details.ts:36:12
[16:33:05] Property 'analytics' does not exist on type 'Window'.
[16:33:05] Error at C:/Users/Breno/Dropbox/Apps/.tmp/pages/item-details/item-details.ts:64:19
[16:33:05] Cannot find name 'Response'.
```

Please go through your app and fix those issue that are printed out.
