### ISSUE TITLE
A change in SCSS file triggers full build in app-scripts: 0.0.43 

### ISSUE THREAD

**Issue by gigocabrera** [driftyco/ionic-app-scripts#387]
#### Short description of the problem:

When I modify a SCSS file (i.e. home.scss) it triggers a full webpack build

#### What behavior are you expecting?

In previous versions, modifying a SCSS file would only trigger sass build and the screen would refresh with your style changes. Now it triggers a full build and although it works fine, it is a little annoying 

**Which @ionic/app-scripts version are you using? 0.0.43

**Comment by Lightheaded** [comment]
Yes, PLEASE fix that! Super-annoying to see the whole page reloaded and having to navigate back.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This has been fixed with the latest version of app-scripts. To install the latest run `npm install @ionic/app-scripts --save-dev`.

**Comment by gigocabrera** [comment]
Awesome! Thank you Justin / @jgw96

**Comment by gigocabrera** [comment]
@jgw96 it still doesn't work as expected. The issue now is that the SCSS changes are not applied at all. In other words, it no longer triggers a full build, just SASS, and it completes according to the console output, but the styles changes are not visible unless you refresh your browser, which defeats the purpose.
