### ISSUE TITLE
Exclude files from tslint

### ISSUE THREAD

**Issue by hermitdemschoenenleben** [driftyco/ionic-app-scripts#482]
Tslint shows errors even for external typescript libraries inside the node_modules folder. I think it would be a good idea to exclude the node_modules folder from tslint or (even better) to create a configuration option for excluding file patterns

**Comment by danbucholtz** [comment]
This should be resolved now. In our `tsconfig.json` we exclude `node_modules`.

Thanks,
Dan

**Comment by chrene** [comment]
I still see vendor code from node_modules being linted

In my case it is the `ng2-img-cropper` module that gets linted. 
`tslint: node_modules/ng2-img-cropper/src/model/point.ts`

my tsconfig.json is

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5"
  },
  "exclude": [
	"node_modules"
  ],
  "include": [
    "src/**/*.ts"
  ],
 "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

**Comment by Domvel** [comment]
@danbucholtz  How? e.g. exclude `src/models` does not work for the linter. He still scans this folder.
