### ISSUE TITLE
Custom decorators are stripped from AoT builds as of 0.0.47

### ISSUE THREAD

**Issue by fiznool** [driftyco/ionic-app-scripts#545]
#### Short description of the problem:

An app which uses custom decorators (e.g. `ngrx/effects`) has those decorators stripped from the resulting production build.

#### What behavior are you expecting?

The custom decorators to not be stripped, as is the case in 0.0.46.

**Steps to reproduce:**
1. Clone the repo https://github.com/fiznool/counter-ionic2-ngrx-effects
2. Switch to the branch `app-scripts-47`
3. Run `npm install`
4. Run `ionic run android --aot` (or `ios`)
5. In the resulting app, increment the counter using the 'Increment' button.
6. Attempt to reset the counter with the 'Reset' button.

The 'Reset' button uses `ngrx/effects`, which in turn depends on a custom decorator, `@Effect`. This is stripped from the build with 0.0.47 so the effect does not run, and hence the counter is not reset.

**Which @ionic/app-scripts version are you using?**

0.0.47

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Using `ngrx/effects` involves a custom decorator, `@Effects`. There are reports elsewhere in the Angular community that custom decorators are stripped from AoT builds in certain conditions (see [here](https://github.com/rangle/angular-2-aot-sandbox#ngrx-effects-top)).

Here is an output of the compiled `effects/counter.ts` module in 0.0.46 and 0.0.47. Notice that the decorators are preserved in the former but stripped in the latter.

**0.0.46**

```
function(module, exports, __webpack_require__) {

"use strict";
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_core__ = __webpack_require__(0);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__ngrx_effects__ = __webpack_require__(254);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2_rxjs_add_operator_map__ = __webpack_require__(538);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2_rxjs_add_operator_map___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_2_rxjs_add_operator_map__);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__reducers_counter__ = __webpack_require__(104);
/* harmony export (binding) */ __webpack_require__.d(exports, "a", function() { return CounterEffects; });
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};




var CounterEffects = (function () {
    function CounterEffects(actions$) {
        this.actions$ = actions$;
        this.reset$ = this.actions$
            .ofType(__WEBPACK_IMPORTED_MODULE_3__reducers_counter__["c" /* RESET */])
            .map(function () { return ({ type: __WEBPACK_IMPORTED_MODULE_3__reducers_counter__["d" /* RESET_SUCCESS */] }); });
    }
    CounterEffects.decorators = [
        { type: __WEBPACK_IMPORTED_MODULE_0__angular_core__["c" /* Injectable */] },
    ];
    /** @nocollapse */
    CounterEffects.ctorParameters = [
        { type: __WEBPACK_IMPORTED_MODULE_1__ngrx_effects__["a" /* Actions */], },
    ];
    __decorate([
        __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_1__ngrx_effects__["b" /* Effect */])(), 
        __metadata('design:type', Object)
    ], CounterEffects.prototype, "reset$", void 0);
    return CounterEffects;
}());
```

**0.0.47**

```
function(module, exports, __webpack_require__) {

"use strict";
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_rxjs_add_operator_map__ = __webpack_require__(534);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_rxjs_add_operator_map___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_0_rxjs_add_operator_map__);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__reducers_counter__ = __webpack_require__(178);
/* harmony export (binding) */ __webpack_require__.d(exports, "a", function() { return CounterEffects; });


var CounterEffects = (function () {
    function CounterEffects(actions$) {
        this.actions$ = actions$;
        this.reset$ = this.actions$
            .ofType(__WEBPACK_IMPORTED_MODULE_1__reducers_counter__["a" /* RESET */])
            .map(function () { return ({ type: __WEBPACK_IMPORTED_MODULE_1__reducers_counter__["b" /* RESET_SUCCESS */] }); });
    }
    return CounterEffects;
}());
```

**Comment by iron9light** [comment]
I think this should be a bug of angular. angular/angular-cli#2799

**Comment by fiznool** [comment]
That issue only applies to the angular cli. Ionic doesn't use the angular
cli so therefore I don't believe it is relevant.

On 14 Dec 2016 12:34, "iron9light" <notifications@github.com> wrote:

I think this should be a bug of angular. angular/angular-cli#2799
<https://github.com/angular/angular-cli/issues/2799>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/driftyco/ionic-app-scripts/issues/545#issuecomment-267022838>,
or mute the thread

**Comment by iron9light** [comment]
1. ionic-cli will call ngc
2. I have the same issue, no matter it's ionic-app-script v0.0.46 or v0.0.47 or even early version.

**Comment by fiznool** [comment]
`ngc` is the angular compiler. This isn't the same as the angular CLI.

I've produced a minimal reproduction via the repository at https://github.com/fiznool/counter-ionic2-ngrx-effects which demonstrates the issue for 0.0.47 but not 0.0.46. So chances are you are seeing some other issue. One thing to watch out for is the syntax for `NgModule`. I found [this resource](https://github.com/rangle/angular-2-aot-sandbox) incredibly helpful to sort out my AoT issues.

**Comment by iron9light** [comment]
Maybe you're right.
But after I use my private version of ngrx/effects which will not depend on any decorator, everything works again.
It's a bug anyway, no matter whose. ;-)

**Comment by danbucholtz** [comment]
This is something we'll need to investigate. We are removing decorators because decorators prevent code from being tree shakeable. We'll chat with Rob for Angular about `ngrx` to see what the correct course of action to take is. Maybe we only remove decorators from code that is processed by AoT. I'm not entirely sure how one would determine that.

Thanks,
Dan

**Comment by Manduro** [comment]
Meanwhile, is there a config option we can use to disable this behaviour?

**Comment by fiznool** [comment]
I don't know if it makes any difference but there is a [temporary fix](https://github.com/angular/angular-cli/commit/db25183341a43eab8f02f33938294a9cac8b5da3) available from the angular team to preserve custom decorators.

**Comment by francesco1992** [comment]
Thank u for the suggestion @fiznool. What file do we need to modify in a Ionic project to get it still works?

**Comment by danbucholtz** [comment]
Hi all,

This is resolved in `0.0.48` which was just published.

Please let me know if you have any issues.

Thanks,
Dan

**Comment by francesco1992** [comment]
I still have the same problem as before.

I've just given a try on @fiznool test repo upgrading app-scripts version to 0.0.48.

**Comment by fiznool** [comment]
@danbucholtz could you confirm that this fix is in place for webpack builds?

I can see from the [relevant commit](https://github.com/driftyco/ionic-app-scripts/commit/45b025530db938f11e8334b72f024e7a504a617d) that this appears to be in place for rollup builds only, but perhaps I'm mistaken.

**Comment by danbucholtz** [comment]
@fiznool,

Yeah, that is the correct commit. I don't think we actually do that process for `webpack` yet.

Thanks,
Dan

**Comment by joewoodhouse** [comment]
I guess this needs to be re-opened yet, if the change hasn't been applied to the default (webpack) build?

**Comment by lleevvyy** [comment]
@fiznool  @joewoodhouse @danbucholtz Decorators are removed in webpack build as well - look at aot-compiler.ts, there is a method removeDecorators from utils/typescript-utils.ts, which is executed during AoT compilation. I've just tested and when removeDecorators are not executed everything works as expected.

**Comment by lleevvyy** [comment]
https://github.com/driftyco/ionic-app-scripts/blob/master/src/aot/aot-compiler.ts#L127

**Comment by danbucholtz** [comment]
@joewoodhouse,

CAn you show me

**Comment by joewoodhouse** [comment]
Something like this? https://github.com/ngrx/example-app/blob/master/src/app/effects/collection.ts

**Comment by fiznool** [comment]
@danbucholtz the most minimal reproduction can be found at the repo linked above in the original issue. It's an Ionic app which uses ngrx/effects.

Here's the link again: https://github.com/fiznool/counter-ionic2-ngrx-effects

**Comment by lleevvyy** [comment]
@danbucholtz Just to clarify - I'm not using ngrx, but rather I have my own decorators for JSON serialization and those decorators are removed as well. I really don't understand why decorators must be removed... I can understand, that angular decorators must be removed in AoT, as they are not needed, but all others are as important and needed as any other js code.

**Comment by danbucholtz** [comment]
Decorators fundamentally make code not tree shakable. We'll do some more experimentation. We're not big fans of decorators as it stands now. We'll have to figure this out.

Thanks,
Dan

**Comment by lleevvyy** [comment]
@danbucholtz Ok, that is a good point, but... afaik webpack by default doesn't do tree shaking?

**Comment by danbucholtz** [comment]
@lleevvyy, it does but not a very good job of it. This is something we're focused on. We want 200KB bundles, not 2000KB bundles 😄 

Thanks,
Dan

**Comment by lleevvyy** [comment]
@danbucholtz Indeed, that would be something :-) In my app's case, js output is almost 3000KB, however... I need those decorators as well :-) :-) Thanks for you work guys, I'm really appreciated!

**Comment by pdrosos** [comment]
I have the exactly same issue. My app's production build is completely broken after the upgrade to ionic 2 rc.4 with ionic-app-scripts 0.0.48, as I use ngrx/store with ngrx/effects almost everywhere. At least now I know the reason. I must temporary downgrade until there's some solution of this issue :(.
@danbucholtz please let us know what to do as soon as possible. Thanks!

**Comment by fiznool** [comment]
If I'm following this correctly, decorators are preserved if you use rollup to build for production. [As per the docs](https://github.com/driftyco/ionic-app-scripts#packagejson-config), setting `"ionic_bundler": "rollup"` in your `package.json` should solve this issue?

**Comment by pdrosos** [comment]
@fiznool I have tried that, but I have issues with 3rd party libraries and rollup. Will see if I can fix them with custom config file, it's not working for now. Thanks!

**Comment by lleevvyy** [comment]
@pdrosos @fiznool An ugly hack (but it works) is to change line 101 of aot-compiler.js (node_modules/@ionic/app-scripts/dist/aot) to below:
```var cleanedFileContent = tsFile.content;```

**Comment by Manduro** [comment]
Meanwhile you can use `ionic-app-scripts build --aot --minifyJs --minifyCss`, which essentially leaves out the `--optimizeJs` that is removing decorators compared to `ionic-app-scripts build --prod`.

**Comment by pdrosos** [comment]
I made a production build with rollup with `ionic build --prod`, but ngrx/effects still doesn't work...
@Manduro thanks, tried that both with rollup and webpack, but it also doesn't work.
It seems to me that the `--aot` makes it stop working, because dev builds work without a problem.

**Comment by pdrosos** [comment]
@lleevvyy Thanks, this one is the only way, which works for me too. Most probably will use it as a temporary hack until a real solution appears.

**Comment by fiznool** [comment]
@lleevvyy great work in figuring out a workaround. I've submitted a PR which adds this in. IMHO the workaround is sound, because this is the approach [the Angular team are taking](https://github.com/angular/angular-cli/commit/db25183341a43eab8f02f33938294a9cac8b5da3) with the `ng` CLI tool.

**Comment by fiznool** [comment]
@danbucholtz has there been any further discussion / progress within the Ionic team regarding this issue?

**Comment by danbucholtz** [comment]
I can merge your PR for `0.0.49`.

Thanks,
Dan

**Comment by danbucholtz** [comment]
This issue will be resolved in `0.0.49` which will go out tomorrow-ish. I'll close the issue when it does.

Thanks,
Dan

**Comment by danbucholtz** [comment]
We published `1.0.0` of app-scripts tonight! 🎉 

Thanks,
Dan
