### ISSUE TITLE
ionic emulate android -l -c == empty logs in console

### ISSUE THREAD

**Issue by djezzzl** [driftyco/ionic-app-scripts#611]
#### Short description of the problem:
Hi, everyone! I have a problem with command:
`ionic emulate android -l -c`
I have two different ways of behavior of that bug:
a) When I have this in my package.json 
> "scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  }

Livereload works well but empty consolelogs:
![2016-12-29 16 23 29](https://cloud.githubusercontent.com/assets/9407725/21545840/aa304b24-cdeb-11e6-9d4a-f2157c117a93.png)

b) When I have this in my package.json
> "scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:watch": "ionic-app-scripts watch"
  }

Some writes in consolelogs but livereload not working
![2016-12-29 16 28 51](https://cloud.githubusercontent.com/assets/9407725/21545925/5d544ff2-cdec-11e6-8955-1e8d1d71ecf7.png)

#### What behavior are you expecting?
 --livereload and --consolelogs work both.

![2016-12-29 16 30 58](https://cloud.githubusercontent.com/assets/9407725/21545970/a1ca4d4e-cdec-11e6-8944-3f856fb4eb7c.png)

Ready to provide any additional information of this bug. Hope on fix because of hard working without livereloading ( I always need consolelogs )

**Comment by moldstadt** [comment]
I have the same issue. I work around it by using the first option to allow
live reload and then use chrome://inspect to view logs.

**Comment by djezzzl** [comment]
@moldstadt I suppose that we should use out-of-the-box opportunities. If they don't work so we should fix it, or remove them and provide anothers with good first look examples/tutorials. So now all talk about easy using --livereload --consolelogs without any saying it's not work now and we are working on it.

**Comment by shreyu86** [comment]
I have same issue with `ionic run android -l -c -s` 
![image](https://cloud.githubusercontent.com/assets/311217/21688288/da2a2c78-d331-11e6-9b55-acc37b998927.png) I see no console logs at all

**Comment by danbucholtz** [comment]
This should be resolved with latest app-scripts and latest ionic from `npm`.

Thanks,
Dan

**Comment by moldstadt** [comment]
@danbucholtz, I am still not seeing console logs when I do ionic run
android -lc. Tested with new project from blank template after adding some
console.log() calls.
Ionic 2.0.0
App-scripts 1.0.0

**Comment by danbucholtz** [comment]
What version of the Ionic CLI are you running? Please do this:

```
npm uninstall -g ionic
npm install -g ionic
```

sudo may be required depending on your environment.

Thanks,
Dan

**Comment by moldstadt** [comment]
@danbucholtz, I am on 2.2.1.
Reinstalled as suggested. Still no console logs.

**Comment by zeornelas** [comment]
Hi @danbucholtz .

I have the same problem. I'm running the last version of ionic on Windows 10:
```
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.5.0
Xcode version: Not installed
```

The log shows in chrome but using -lc it doesn't redirect the output to the cli.

I tried it with a new project using `ionic start NEWPROJECT --tabs --v2` and I'm not getting the logs.

Were you able to solve this?

**Comment by jthoms1** [comment]
@zeornelas Can you provide the first ~50 lines of output when you execute serve with `-lc`?

**Comment by zeornelas** [comment]
@jthoms1 Here it is the full log:
```
PS <!!!!!MYPATH!!!!!>\NEWPROJECT> ionic run android -lc
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

> ionic-hello-world@ ionic:serve <!!!!!MYPATH!!!!!>\NEWPROJECT
> ionic-app-scripts serve "--v2" "--runLivereload" "--isPlatformServe" "--consolelogs" "--livereload" "--port" "8100" "--livereload-port" "35729" "--address" "192.168.1.13" "--iscordovaserve" "--nobrowser"

[17:13:00]  ionic-app-scripts 1.0.0
[17:13:00]  watch started ...
[17:13:00]  build dev started ...
[17:13:00]  clean started ...
[17:13:00]  clean finished in 1 ms
[17:13:00]  copy started ...
[17:13:00]  transpile started ...
[17:13:03]  transpile finished in 2.84 s
[17:13:03]  webpack started ...
[17:13:03]  copy finished in 3.05 s
[17:13:09]  webpack finished in 5.56 s
[17:13:09]  sass started ...
[17:13:09]  sass finished in 719 ms
[17:13:09]  build dev finished in 9.16 s
[17:13:10]  watch ready in 9.26 s
[17:13:10]  dev server running: http://192.168.1.13:8100/


You have been opted out of telemetry. To change this, run: cordova telemetry on.

ANDROID_HOME=<!!!!!ANDROID_PATH!!!!!>

JAVA_HOME=C:\Program Files\java\jdk1.8.0_121

Subproject Path: CordovaLib

Starting a new Gradle Daemon for this build (subsequent builds will be faster).

Incremental java compilation is an incubating feature.

:preBuild
 UP-TO-DATE

:preDebugBuild
 UP-TO-DATE

:checkDebugManifest


:CordovaLib:preBuild
 UP-TO-DATE

:CordovaLib:preDebugBuild
 UP-TO-DATE

:CordovaLib:checkDebugManifest


:CordovaLib:prepareDebugDependencies

:CordovaLib:compileDebugAidl


:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint
 UP-TO-DATE
:CordovaLib:mergeDebugShaders


:CordovaLib:compileDebugShaders


:CordovaLib:generateDebugAssets
:CordovaLib:mergeDebugAssets


:CordovaLib:mergeDebugProguardFiles


:CordovaLib:packageDebugRenderscript
 UP-TO-DATE

:CordovaLib:compileDebugRenderscript


:CordovaLib:generateDebugResValues


:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources


:CordovaLib:processDebugManifest


:CordovaLib:generateDebugBuildConfig


:CordovaLib:processDebugResources


:CordovaLib:generateDebugSources

:CordovaLib:incrementalDebugJavaCompilationSafeguard


:CordovaLib:compileDebugJavaWithJavac


:CordovaLib:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug


:CordovaLib:mergeDebugJniLibFolders


:CordovaLib:transformNative_libsWithMergeJniLibsForDebug


:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug


:prepareAndroidCordovaLibUnspecifiedDebugLibrary


:prepareDebugDependencies
:compileDebugAidl


:compileDebugRenderscript


:generateDebugBuildConfig


:generateDebugResValues


:generateDebugResources


:mergeDebugResources


:processDebugManifest


:processDebugResources


:generateDebugSources
:incrementalDebugJavaCompilationSafeguard


:compileDebugJavaWithJavac


:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

Note: <!!!!!MYPATH!!!!!>\NEWPROJECT\platforms\android\src\org\apache\cordova\splashscreen\SplashScreen.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

:compileDebugNdk
 UP-TO-DATE

:compileDebugSources
:mergeDebugShaders


:compileDebugShaders


:generateDebugAssets

:mergeDebugAssets


:transformClassesWithDexForDebug


:mergeDebugJniLibFolders


:transformNative_libsWithMergeJniLibsForDebug


:processDebugJavaRes
 UP-TO-DATE

:transformResourcesWithMergeJavaResForDebug


:validateSigningDebug
:packageDebug


:assembleDebug
:cdvBuildDebug



BUILD SUCCESSFUL



Total time: 34.717 secs

Built the following apk(s):
        <!!!!!MYPATH!!!!!>/NEWPROJECT/platforms/android/build/outputs/apk/android-debug.apk


ANDROID_HOME=<!!!!!ANDROID_PATH!!!!!>

JAVA_HOME=C:\Program Files\java\jdk1.8.0_121

No target specified and no devices found, deploying to emulator


Skipping build...

Built the following apk(s):
        <!!!!!MYPATH!!!!!>/NEWPROJECT/platforms/android/build/outputs/apk/android-debug.apk

Using apk: <!!!!!MYPATH!!!!!>/NEWPROJECT/platforms/android/build/outputs/apk/android-debug.apk

Package name: com.ionicframework.newproject515834

INSTALL SUCCESS

LAUNCH SUCCESS
```

**Comment by zeornelas** [comment]
@jthoms1 @danbucholtz Hi guys.
I just realized that it logs to the console if I run it in my phone but if run it in a virtual device it shows nothing. I'm running Android 6.0 in both devices (physical and virtual). I don't know if this helps debug the problem.

@djezzzl Your problem was with a physical or a virtual device?

**Comment by djezzzl** [comment]
Yes, I still see nothing but I tested only on virtual device.

2 февр. 2017 г. 19:00 пользователь "zeornelas" <notifications@github.com>
написал:

**Comment by moldstadt** [comment]
I have also only tested on Genymotion, not a physical device.

**Comment by zeornelas** [comment]
I'm using the virtual device from the AVD manager.
