### ISSUE TITLE
Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by chack** [driftyco/ionic-app-scripts#64]
Ionic Serve runs without problems, but Ionic run iOS gives me this:
I already updated to app-scripts 0.0.27 to get #44

> [16:22:46]  bundle prod started ...
<--- Last few GCs --->
  167123 ms: Mark-sweep 1308.5 (1434.1) -> 1308.5 (1434.1) MB, 1012.0 / 0.0 ms [allocation failure] [GC in old space requested].
  168098 ms: Mark-sweep 1308.5 (1434.1) -> 1308.5 (1434.1) MB, 975.3 / 0.0 ms [allocation failure] [GC in old space requested].
  169101 ms: Mark-sweep 1308.5 (1434.1) -> 1318.0 (1418.1) MB, 1002.5 / 0.0 ms [last resort gc].
  170079 ms: Mark-sweep 1318.0 (1418.1) -> 1327.5 (1418.1) MB, 977.2 / 0.0 ms [last resort gc].
<--- JS stacktrace --->
==== JS stack trace =========================================
Security context: 0x1de7fe7cfb51 <JS Object>
    1: decode(aka decode) [/Users/Jan/Documents/Wohntraum360/wohntraumapp_v2/wohntraumapp/node_modules/rollup/dist/rollup.js:~304] [pc=0x890dfd2cecf] (this=0x1de7fe704381 <undefined>,mappings=0x2036de204201 <Very long string[11559331]>)
    2: render [/Users/Jan/Documents/Wohntraum360/wohntraumapp_v2/wohntraumapp/node_modules/rollup/dist/rollup.js:8938] [pc=0x890e04420e6] (this=0x63e3a0f75d1 <a...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 
node::Abort() [/usr/local/bin/node]
 2: 
node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: 
v8::internal::V8::FatalProcessOutOfMemory(char const*, bool)
 [/usr/local/bin/node]
 4: 
v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/local/bin/node]
 5: 
v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 6: 
0x890dfc079a7
Caught exception:
 undefined

**Comment by jgw96** [comment]
Hello @chack would you mind running `npm install` inside your app and seeing if you still run into this issue? The latest app-scripts includes a fix for this issue.

**Comment by chack** [comment]
@jgw96 see https://github.com/driftyco/ionic-cli/issues/1453#issuecomment-251129597

**Comment by adamdbradley** [comment]
@chack If you don't add the `--max-old-space-size=2048` flag, do you still get the errors with the latest app-scripts?

**Comment by Manduro** [comment]
Ran into this using 0.0.28:
```
[13:00:41]  templateUpdate started ...
[13:00:41]  bundle dev update started ...
<--- Last few GCs --->
 1419503 ms: Mark-sweep 1262.8 (1438.9) -> 1262.8 (1438.9) MB, 3390.2 / 0.0 ms [allocation failure] [GC in old space requested].
 1422541 ms: Mark-sweep 1262.8 (1438.9) -> 1262.8 (1438.9) MB, 3037.0 / 0.0 ms [allocation failure] [GC in old space requested].
 1425939 ms: Mark-sweep 1262.8 (1438.9) -> 1273.9 (1420.9) MB, 3397.1 / 0.0 ms [last resort gc].
 1429769 ms: Mark-sweep 1273.9 (1420.9) -> 1285.1 (1420.9) MB, 3829.0 / 0.0 ms [last resort gc].
<--- JS stacktrace --->
==== JS stack trace =========================================
Security context: 0x2c7804cfb51 <JS Object>
    1: decode(aka decode) [/Users/user/etc/etc/etc/node_modules/rollup/dist/rollup.js:~302] [pc=0x33a2e24d8a59] (this=0x2c780404381 <undefined>,mappings=0xbbe3fa04201 <Very long string[3487733]>)
    2: render [/Users/etc/etc/etc/node_modules/rollup/dist/rollup.js:8971] [pc=0x33a2e2ce9947] (this=0x3b1e918ab8c1 <a Bundle with map 0x326f83434f9>,options=0x3d04914d2cf9 <a...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/user/.nvm/versions/node/v6.7.0/bin/node]
 2: 
node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>)
 [/Users/user/.nvm/versions/node/v6.7.0/bin/node]
 3: 
v8::internal::V8::FatalProcessOutOfMemory(char const*, bool)
 [/Users/user/.nvm/versions/node/v6.7.0/bin/node]


 4: 
v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/user/.nvm/versions/node/v6.7.0/bin/node]
 5: 
v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/user/.nvm/versions/node/v6.7.0/bin/node]
 6: 
0x33a2e1f079a7
 7: 0x33a2e24d8a59
 8: 0x33a2e2ce9947
```

**Comment by cmaart** [comment]
Can confirm this as well for 0.0.28

**Comment by mirkonasato** [comment]
To summarise my comments on #85, this patch fixes it for me: https://gist.github.com/mirkonasato/903e039bf341707776c402497afc25bb

**Comment by shlomiassaf** [comment]
Can confirm this as well for 0.0.28

Error:
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

<--- Last few GCs --->
  154894 ms: Scavenge 1399.5 (1456.8) -> 1399.5 (1456.8) MB, 3.4 / 0 ms (+ 1.3 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
  156028 ms: Mark-sweep 1399.5 (1456.8) -> 1391.4 (1456.8) MB, 1133.6 / 0 ms (+ 1.3 ms in 1 steps since start of marking, biggest step 1.3 ms) [last resort gc].
  157282 ms: Mark-sweep 1391.4 (1456.8) -> 1393.2 (1456.8) MB, 1253.7 / 0 ms [last resort gc].
<--- JS stacktrace --->
==== JS stack trace =========================================
Security context: 0x3968415e3ac1 <JS Object>
    1: /* anonymous */(aka /* anonymous */) [/Users/shlomiassaf/Desktop/Cisco/IONIC/ionic-app-scripts/node_modules/rollup/dist/rollup.js:~8365] [pc=0x3e2e6953d3cc] (this=0x396841504189 <undefined>,line=0x181e0e1b6221 <JS Array[12]>)
    2: arguments adaptor frame: 3->1
    3: InnerArrayMap(aka InnerArrayMap) [native array.js:~1019] [pc=0x3e2e69562746] (this=0x396841504189 <undefined>,bl=0x2a2a5...
```

Happens around the 5th watch code update.

**Comment by Aristona** [comment]
+1, happens to me too on both 0.0.27 and 0.0.28

**Comment by lleevvyy** [comment]
Confirm, happens to to me as well on 0.0.28.

**Comment by UISTRepo** [comment]
+1

**Comment by lleevvyy** [comment]
@adamdbradley Does the flag ```--max-old-space-size=2048``` should help ```ionic serve``` to avoid out of memory?

**Comment by chack** [comment]
@lleevvyy yes it does, see my comment above

**Comment by lleevvyy** [comment]
@chack Ok, thanks.

**Comment by chack** [comment]
@lleevvyy for clarification: you have to paste it into the package.json as is wrote in the comment and not as flag in the terminal. Then you can clearly see the benefit. If you run serve too long it will get the error still sometimes :( but a lot less!

**Comment by mirkonasato** [comment]
There's a memory leak, raising the max size will only delay the limit being reached. The solution is removing the leak.

**Comment by Aristona** [comment]
@adamdbradley @jgw96 Any progress about this issue? It is really hard to work with Ionic 2 while this problem exists.

**Comment by jgw96** [comment]
Hello everyone! We are actively working on this issue and I am happy to report that I am testing the latest master right now and it seems to be fixed for good this time 😃 . Ive also added some debug logging of the memory usage so that we can keep an eye on this in the future.

**Comment by tuntev** [comment]
When this will be available for us? Should we just reinstall the node_modules, or some other changes are required?

**Comment by jgw96** [comment]
We are working hard to get a new release out asap. Thanks!

**Comment by jgw96** [comment]
Hello everyone! We just release v0.0.29 of app-scripts which fixes this memory leak. To update simply run `npm install` in your project. If you all could give that a try and see if it fixes the issue that would be awesome!

**Comment by TheBrockEllis** [comment]
Haven't been able to test out the garbage collection/memory error on v0.0.29 yet because Tippex found an error in one of my components and breaks the dev build.

```
[23:21:32]  bundle dev failed:  Error transforming /path/to/app/src/pages/page/page.ts with 'ion-compiler' plugin: rollup-plugin-typescript: Unexpected character (125:5). If this is valid JavaScript, it's probably a bug in tippex. Please raise an issue at https://github.com/Rich-Harris/tippex/issues – thanks!


    });

      ^; when processing: '/path/to/app/src/pages/page/page.ts'
```

That component passes the Atom Typescript linter just fine and that component was running perfect prior to upgrading to v0.0.29 (was on v0.0.23 prior, I believe). Anyone else see something similar?

**Comment by Manduro** [comment]
I'm running into invalid compilation errors as well, only since v0.0.29.
`definitions.ts` definitely does export interface `IMessage`. (related? https://github.com/rollup/rollup-plugin-typescript/issues/65)

```
[09:32:34]  ionic-app-scripts 0.0.29
[09:32:34]  watch started ...
[09:32:34]  build dev started ...
[09:32:34]  clean started ...
[09:32:34]  clean finished in 32 ms
[09:32:34]  copy started ...
[09:32:34]  bundle dev started ...
[09:32:34]  lint started ...
[09:32:35]  copy finished in 585 ms
[09:32:46]  lint finished in 11.83 s
[09:32:58]  bundle dev failed:  Module /path/to/src/definitions.ts does not export IMessage (imported by /path/to/src/components/message/message.ts)

[09:32:58]  Error: Module /path/to/src/definitions.ts does not export IMessage (imported by /path/to/src/components/message/message.ts)
    at Module.trace (/path/to/node_modules/rollup/dist/rollup.js:7706:29)
    at ModuleScope.findDeclaration (/path/to/node_modules/rollup/dist/rollup.js:7329:22)
    at Scope.findDeclaration (/path/to/node_modules/rollup/dist/rollup.js:5349:39)
    at Identifier.bind (/path/to/node_modules/rollup/dist/rollup.js:6497:29)
    at /path/to/node_modules/rollup/dist/rollup.js:5149:50
    at UnaryExpression.eachChild (/path/to/node_modules/rollup/dist/rollup.js:5166:5)
    at UnaryExpression.bind (/path/to/node_modules/rollup/dist/rollup.js:5149:7)
    at UnaryExpression.bind (/path/to/node_modules/rollup/dist/rollup.js:6893:53)
    at /path/to/node_modules/rollup/dist/rollup.js:5149:50
    at BinaryExpression.eachChild (/path/to/node_modules/rollup/dist/rollup.js:5166:5)
```

Reverting to v0.0.28 gets me running again. Back to the out of memory errors for now I guess!

**Comment by UISTRepo** [comment]
I deleted the old node_modules, and reinstalled them again. app-scripts are now 0.0.29. The build time on the live reload takes around 10 secs, the ionic build takes around 70 secs. All seems fine, no memory errors.
Also `ionic run <platform>` goes without errors while `ionic serve` is still on. This was a problem on 0.0.28. 
If you can improve the loading time it would be great.

**Comment by mirkonasato** [comment]
I can confirm I no longer get the out of memory error. Memory usage increases and updates get slower at first, but after 10 updates or so it somehow stabilises: [pastebin.com/kpJcUGMG](http://pastebin.com/kpJcUGMG)

**Comment by jgw96** [comment]
Thanks for all the testing everyone! @TheBrockEllis So its possible that this is a bug in tippex, but its also possible that its a bug in the typescript plugin in atom. Does tsc throw an error about that component? Also, if you have vscode installed you can check your component there too. The Atom typescript plugin can be a little weird sometimes, but from my experience vscode is more reliable when it comes to type checking etc. Could you share a repo that includes the code that is causing the error? @Manduro Could you share the code that is causing the error? @mirkonasato This seems normal. Its more memory usage than im seeing on my machine with my project, but your project may be bigger. It is normal for memory usage to climb at first and then stabilize.

**Comment by TheBrockEllis** [comment]
@jgw96 color me ashamed. My error had nothing to do with Tippex or the new release of the app-scripts. I found a stray backtick (`)in my template HTML file when starting to create an isolated repo to share. Removing that small little typo fixed everything. I'll report back with my experience with v0.0.29. Thanks!

**Comment by jgw96** [comment]
@Manduro can you try renaming your definitions file to definitions.d.ts?

**Comment by 10freefingers** [comment]
With the update of app-scripts to 0.0.29 my interface exports don't work anymore.
Before I could define them like this in src/providers/data/model.ts:
`export interface MyData { name: string } `

And import it in a page like src/pages/data/view.ts:
`import { MyData } from '../../providers/data/model'`

Now I get the error:

> Error: Module .... model.ts does not export MyData (imported by ... view.ts)

Has the use of interface exports in Typescript changed and this error occurs now just because of some different option in app-scripts?

**Comment by Manduro** [comment]
@jgw96 Exact same here as @10freefingers. Sorry for the confusing filename, but my `definitions.ts` has only exported interfaces and types that I use all over the application, so it's not really a `d.ts` file.

**Comment by aperezbaena-csc** [comment]
Same issue as @10freefingers and @Manduro exporting interfaces with app-scripts 0.0.30.

**Comment by RyanMcDonald** [comment]
Same issue here with broken interfaces. Downgraded to 0.0.28 in the meantime.

**Comment by jgw96** [comment]
Hello all! I am going to close this issue for now as this specific memory issue has been fixed in v0.0.30. Just for full disclosure, there is another memory issue that is being actively worked on, and that 0.0.31 should go towards fixing. Thanks everyone!

**Comment by nnixaa** [comment]
Hey @jgw96, still seeing this, can't really find steps to reproduce it - happens accidentally after some changes in the code while running `ionic serve`:
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

<--- Last few GCs --->

  544163 ms: Mark-sweep 1386.9 (1457.0) -> 1392.3 (1457.0) MB, 1335.4 / 0 ms [allocation failure] [GC in old space requested].
  545503 ms: Mark-sweep 1392.3 (1457.0) -> 1392.3 (1457.0) MB, 1339.8 / 0 ms [allocation failure] [GC in old space requested].
  546834 ms: Mark-sweep 1392.3 (1457.0) -> 1384.5 (1457.0) MB, 1330.6 / 0 ms [last resort gc].
  548148 ms: Mark-sweep 1384.5 (1457.0) -> 1386.5 (1457.0) MB, 1313.8 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x126a479e3ac1 <JS Object>
    1: findDeclaration [/Users/nixa/Development/Projects/Kompartment/Kompartment/node_modules/rollup/dist/rollup.js:~5359] [pc=0x2fc2c0755ed4] (this=0x3a23996ea6d1 <a Scope with map 0x300771ab0b61>,name=0x126a4795e3f9 <String[1]: i>)
    2: bind [/Users/nixa/Development/Projects/Kompartment/Kompartment/node_modules/rollup/dist/rollup.js:6516] [pc=0x2fc2c34eb124] (this=0x3435a6aae4f9 <a Node wit...
``` 
my env is:
```
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.41
ios-deploy version: 1.9.0
ios-sim version: 5.0.10
OS: Mac OS X El Capitan
Node Version: v5.11.0
Xcode version: Xcode 8.0 Build version 8A218a
```

**Comment by shreekantha** [comment]
Hey @jgw96 I am also facing the same issue.

Below is the my package.json

{
  "name": "dhI",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.7",
    "ionic-angular": "2.1.0",
    "ionic-native": "2.4.1",
    "ionicons": "3.0.0",
    "ng2-googlechart": "^2.1.0",
    "rxjs": "5.0.0-beta.12",
    "sw-toolbox": "3.4.0",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.1.3",
    "typescript": "2.0.10"
  },
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard",
    "cordova-plugin-statusbar"
  ],
  "cordovaPlatforms": [],
  "description": "dhI: An Ionic project"
}

**Comment by timothybclayton** [comment]
I've was able to workaround this issue on Ionic v3.5, Ionic cli 3.4.0, and Node.js 6.9.1. We have a big app with lots of modules and heap space errors occurring every build, whether "ionic serve", or "ionic cordova run --prod". 

Modify your ionic.cmd file in C:\Users\<user>\AppData\Roaming\npm by adding --max_old_space_size. I set mine to 8096.

@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe" **--max_old_space_size=8048** "%~dp0\node_modules\ionic\bin\ionic" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node **--max_old_space_size=8048** "%~dp0\node_modules\ionic\bin\ionic" %*
)

Good luck!

**Comment by phonic** [comment]
@timothybclayton You've saved my friday. Thanks a lot!

**Comment by bkarv** [comment]
Does anyone know how to increase the node memory in OSX?

**Comment by bigthing33** [comment]
Does anyone know how to increase the node memory in OSX?

**Comment by bkarv** [comment]
@bigthing33 hey mate this worked for me:

1. Upgrade to Typescript 2.6.1 (or latest) ie npm install typescript@latest

2. Upgrade Ionic, Ionic Scripts and Ionic CLI TIP: Run  'ionic doctor check' and do the suggested upgrades

3. Increased my memory for the build by adding this to the package.json to scripts section as a seperate line:
"ionic:build": "node --max-old-space-size=8192 ./node_modules/@ionic/app-scripts/bin/ionic-app-scripts.js build"

4. In terminal Ran 'npm run ionic:build --prod' It is important you get the exact text, if it is correct the terminal will print something like:
node --max-old-space-size=8192 ./node_modules/@ionic/app-scripts/bin/ionic-app-scripts.js build

Note if you still have out of memory issues, try increasing the ram further. I currently have it at 12228 as I have big app. Best of luck!

**Comment by bicibg** [comment]
ok how is this still an issue after 2 years. I am still getting this error. I tried what @bkarv said but then i get "#FailureMessage Object: 0x7febe7443950Illegal instruction (core dumped)"
`cli packages: (/home/bugra/.linuxbrew/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v10.0.0
    npm               : 5.6.0 
    OS                : Linux 4.4

Environment Variables:

    ANDROID_HOME : /home/bugra/Android/Sdk

Misc:

    backend : legacy
`

**Comment by khaled-elrifaay** [comment]
@timothybclayton how to do it in linux

**Comment by pascalwhoop** [comment]
also running into this on linux on node 10.9 ionic cli 4.1.2 
```
[18:10:43]  copy finished in 5.03 s 

<--- Last few GCs --->

[32515:0x5604aa886a70]    26126 ms: Scavenge 1385.7 (1422.9) -> 1385.1 (1423.4) MB, 2.4 / 0.0 ms  (average mu = 0.171, current mu = 0.089) allocation failure 
[32515:0x5604aa886a70]    26130 ms: Scavenge 1385.9 (1423.4) -> 1385.3 (1423.9) MB, 2.4 / 0.0 ms  (average mu = 0.171, current mu = 0.089) allocation failure 
[32515:0x5604aa886a70]    26134 ms: Scavenge 1386.1 (1423.9) -> 1385.5 (1424.9) MB, 2.4 / 0.0 ms  (average mu = 0.171, current mu = 0.089) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0xf4c117dc01d]
Security context: 0x3fe8a951e549 <JSObject>
    1: signatureToSignatureDeclarationHelper(aka signatureToSignatureDeclarationHelper) [0x11a4942fd539] [/home/pascalwhoop/Documents/Code/show-your-boots.org/node_modules/typescript/lib/typescript.js:~26245] [pc=0xf4c12ae9aa5](this=0x2983ca6026f1 <undefined>,signature=0x1326ff9c3ad1 <SignatureObject map = 0xfb048b8ff09>,kind=160,context=0x328bfd49b811 <Objec...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x5604a7ff9101 node::Abort() [node]
 2: 0x5604a7ff914f  [node]
 3: 0x5604a81bad72 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0x5604a81bafcb v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0x5604a854f313  [node]
 6: 0x5604a854f454  [node]
 7: 0x5604a855f0d3 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0x5604a855fa59 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0x5604a8561b6d v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
10: 0x5604a8561bc2 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
11: 0x5604a852fd65 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
12: 0x5604a87a23ff v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
13: 0xf4c117dc01d 
[ERROR] Non-zero exit from subprocess.
```
when running `ionic build --prod --minifyjs --minifycss --optimizejs --engine browser`
