### ISSUE TITLE
Template changes don't live reload

### ISSUE THREAD

**Issue by moldstadt** [driftyco/ionic-app-scripts#724]
#### Short description of the problem:
Since upgrading to app-scripts 1.0.1, making a change in a template file doesn't reflect in the browser while serving my project.  I need to stop serving and serve again to see the changes.  Using app-scripts 1.0.0 works as expected.

#### What behavior are you expecting?
Changes to template files should be pushed to the app in the browser.

**Steps to reproduce:**
1.  ionic serve
2.  change something in a template file
3.  after building, the template hasn't changed in the browser

**Which @ionic/app-scripts version are you using?**
1.0.1 (1.0.0 works as expected)

**Comment by darron1217** [comment]
This happens on my project to...
This is my cmd log (I'm working on Window10)

[20:50:59]  ionic-app-scripts 1.0.1
[20:50:59]  watch started ...
[20:50:59]  build dev started ...
[20:50:59]  preprocess started ...
[20:50:59]  preprocess finished in less than 1 ms
[20:50:59]  clean started ...
[20:50:59]  clean finished in 21 ms

[20:50:59]  copy started ...
[20:50:59]  transpile started ...
[20:51:02]  transpile finished in 2.87 s
[20:51:02]  webpack started ...
[20:51:02]  copy finished in 3.15 s
[20:51:10]  webpack finished in 7.90 s
[20:51:10]  sass started ...
[20:51:11]  sass finished in 1.74 s
[20:51:11]  lint started ...
[20:51:11]  postprocess started ...
[20:51:11]  postprocess finished in less than 1 ms
[20:51:11]  build dev finished in 12.56 s
[20:51:12]  watch ready in 12.96 s
[20:51:12]  dev server running: http://localhost:8100/

[20:51:15]  lint finished in 3.98 s
[20:51:23]  build started ...
[20:51:23]  transpile started ...
[20:51:26]  transpile finished in 2.30 s
[20:51:26]  webpack update started ...
[20:51:26]  webpack update finished in 701 ms
[20:51:26]  build finished in 3.01 s

**Comment by moldstadt** [comment]
I get the same output.  With app scripts 1.0.0, after changing a template, I get the following output:
```
[14:05:20]  build started ...
[14:05:21]  template update started ...
[14:05:21]  template update finished in 138 ms
[14:05:21]  build finished in 141 ms
```

**Comment by nowzig** [comment]
I can confirm this problem as well.

**Comment by danbucholtz** [comment]
This is fixed in master, will go out later today. Sorry about that.

Thanks,
Dan

**Comment by moldstadt** [comment]
Thanks @danbucholtz 
Not sure if this is in the latest nightly (1.0.1-201702081907) yet, but it is still not working.  I now sometimes get the logs showing that the template is being updated and sometimes not.  However, the template is not updated in either case.

**Comment by danbucholtz** [comment]
It should be fixed in nightly unless someone overwrote my `nightly` build with a master branch. It's possible, we are testing several things concurrently. 

[This](https://github.com/driftyco/ionic-app-scripts/commit/1128c9ca4acbb64d6df03bed40878ea9775fb577) one liner copy/paste is the change you'd need to make to get it working again. For now you could just do it in your project's node_modules/@ionic/app-scripts/config/webpack.config.js file.

Thanks,
Dan

**Comment by mxth** [comment]
So, if cannot use `[name].js`, how can we have multiple entry bundles?

**Comment by mordka** [comment]
Out of nowhere, we started to have this problem using the latest stack. Version downgrades and code rollback didn't help, so I'm still investigating.
