### ISSUE TITLE
1.2.2 "ionic serve" just hangs and not responding

### ISSUE THREAD

**Issue by anton-white** [driftyco/ionic-app-scripts#858]
Ionic 2
app-scripts 1.2.2

After I updated ionic-app-scripts from 1.1.4 to the latest 1.2.2, `ionic serve` just hangs without any error message.

I tried setting up a new project with `ionic start testIonic --v2` and experienced the same behavior.

**Comment by danbucholtz** [comment]
@anton-white,

That seems strange to me. How can I recreate it?

Thanks,
Dan

**Comment by anton-white** [comment]
@danbucholtz 
```
$ npm list -g --depth=0
/usr/lib
├── cordova@6.5.0
├── ionic@2.2.1
├── npm@4.4.1
├── source-map-explorer@1.3.3
└── typescript@2.2.1
```
1. `ionic start testIonic --v2`
2. `cd testIonic`
3. `ionic serve`

**Comment by pawelkat** [comment]
I can confirm the behavior, just hangs after ionic serve. (Ubuntu)

**Comment by anton-white** [comment]
Me too on Ubuntu 16.04 desktop

**Comment by pawelkat** [comment]
I have downgraded the version of app-scripts to 1.1.4 with npm install @ionic/app-scripts@1.1.4 --save-dev. Now it works

**Comment by anton-white** [comment]
Man, that's cool :)
but if you look closer at my initial message:
> After I updated ionic-app-scripts from 1.1.4 to the latest 1.2.2

**Comment by Gengjun-VVU** [comment]
This is the issue right now, there are few issues open at ionic-cli repo, the fix so far is to downgrade it back to 1.1.4 as suggested by @pawelkat. However, I think we are looking for the long term fix, which is fix in the latest script rather than downgrade.

**Comment by UAEpro** [comment]
i have the same problem ... fix it with downgrading
`npm install @ionic/app-scripts@1.1.4 --save-dev`

**Comment by rashnk** [comment]
i have the same problem ... fix it with downgrading
npm install @ionic/app-scripts@1.1.4 --save-dev

**Comment by danbucholtz** [comment]
Are you all on linux? There is a known issue fixed in `nightly` for linux.

Thanks,
Dan

**Comment by rashnk** [comment]
@danbucholtz  no, windows 7 
@ionic/app-scripts@1.1.4 up all versions not working,
1.1.4  works

**Comment by danbucholtz** [comment]
This should be working now with `1.2.3`. Can you please let me know if it's not and I'll re-open.

Thanks,
Dan

**Comment by anton-white** [comment]
@danbucholtz,
it's working now. Thanks a lot!

**Comment by Doaaxv** [comment]
I still have this same problem and I tried many things but still,
my operating system is windows 8.
